### ISSUE TITLE
Fix flaky o-layout test

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami#329]
```
    Layout > .init() > updates `aria-current` on init for manually constructed navigation markup
    	AssertionError: location == false
    	    at Function.proclaim.equal (/home/runner/work/origami/origami/tools/origami-build-tools/node_modules/proclaim/lib/proclaim.js:38:4)
	    at test/layout.test.js:503:24
```

this test fails on CI all the time and it's really annoynig

**Comment by chee** [comment]
I'm moving this from `next` to `current` because I think it's a priority. It's really annoying seeing an o-layout failure on nearly every PR.

**Comment by chee** [comment]
Did this test failure coincide with the code for switching to `IntersectionObserver`? Do we need to wait longer, or come up with another strategy?

**Comment by chee** [comment]
oh, i did this

**Comment by chee** [comment]
re-opening this because the test is flaky again
